name: futebol
description: A Flutter project for underground football club to find its perfect match

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  flutter_bloc: ^8.1.1
  scoped_model: ^2.0.0
  get_it: ^7.2.0
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  step_progress_indicator: ^1.0.2
  intl: ^0.17.0
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  firebase_storage: ^10.0.3
  cloud_firestore: ^2.5.3
  image_picker: ^0.8.6
  flutter_svg: ^1.1.6
  page_transition: ^2.0.9
  flutter_map: ^3.1.0
  latlong2: ^0.8.0
  geocoding: ^2.0.5
  cached_network_image: ^3.2.3
dependency_overrides:
  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo.png"
  min_sdk_android: 21
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/static/Montserrat-Regular.ttf
        - asset: fonts/static/Montserrat-Bold.ttf
          weight: 700
    - family: Merriweather
      fonts:
        - asset: fonts/Merriweather-Regular.ttf
        - asset: fonts/Merriweather-Bold.ttf
          weight: 700